### ISSUE TITLE
What's the transpile option for?

### ISSUE THREAD

**Issue by andresespinosapc** [bicouy0/nuxt3-urql#239]
In `nuxt.config.js`, what's the following option for?
```
build: {
  transpile: ["@urql/vue"]
}
```

I tried removing it and everything seems to still be working.

**Comment by bicouy0** [comment]
If you remove this your dev will work ok.

But when you build and put your code to production you will get : "[nuxt] [request error] use* functions may only be called during the `setup()` or other lifecycle hooks." at at useClient (./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:47:11)
